"""
seed_data.py
-------------
The BuildPath project catalog - around 32 real-world projects spread
across 8 categories (AI/ML, Data Science, Web Development, Backend
Development, Cybersecurity, App Development, Productivity, and
College/Student problems).

Each project is a Python dictionary with every field the recommendation
engine and the templates need: difficulty, hours, required/learned
skills, career relevance, interests, the real-world problem it solves,
tech stack, learning outcomes, and a step-by-step roadmap.

seed_if_needed() only inserts this data the FIRST time the app runs
(it checks if the projects table is already populated), so restarting
the app won't create duplicates.
"""

import models

PROJECTS = [

    # ============================================================
    # AI / ML
    # ============================================================
    {
        "title": "Spam Email Classifier",
        "category": "AI/ML",
        "difficulty": "Easy",
        "estimated_hours": 15,
        "duration_weeks": 1,
        "required_skills": ["Python"],
        "learned_skills": ["Machine Learning", "Pandas", "Scikit-learn"],
        "prerequisites": "Basic Python syntax and functions",
        "career_relevance": ["AI/ML Engineer", "Data Scientist"],
        "interests": ["Productivity", "Social Good"],
        "real_world_problem": "Inboxes get flooded with spam, and rule-based filters are easy to bypass.",
        "technologies": ["Python", "Scikit-learn", "Pandas"],
        "learning_outcomes": ["Text preprocessing", "Naive Bayes classification", "Model evaluation"],
        "roadmap": [
            "Collect/download a labeled spam-vs-ham email dataset",
            "Clean and preprocess the text (tokenize, remove stopwords)",
            "Convert text to features using CountVectorizer/TF-IDF",
            "Train a Naive Bayes classifier and evaluate accuracy",
            "Build a simple CLI to test new emails",
        ],
    },
    {
        "title": "House Price Predictor",
        "category": "AI/ML",
        "difficulty": "Easy",
        "estimated_hours": 12,
        "duration_weeks": 1,
        "required_skills": ["Python", "Statistics"],
        "learned_skills": ["Machine Learning", "Pandas", "Data Visualization"],
        "prerequisites": "Basic statistics (mean, correlation)",
        "career_relevance": ["AI/ML Engineer", "Data Scientist"],
        "interests": ["Finance"],
        "real_world_problem": "Buyers and sellers often don't know if a house is priced fairly for its area.",
        "technologies": ["Python", "Scikit-learn", "Matplotlib"],
        "learning_outcomes": ["Linear regression", "Feature engineering", "Data visualization"],
        "roadmap": [
            "Load a housing dataset (e.g. Boston/California housing)",
            "Explore and visualize relationships between features and price",
            "Handle missing values and engineer useful features",
            "Train a linear regression model",
            "Evaluate with RMSE and visualize predictions vs actual",
        ],
    },
    {
        "title": "Movie Recommendation System",
        "category": "AI/ML",
        "difficulty": "Medium",
        "estimated_hours": 25,
        "duration_weeks": 2,
        "required_skills": ["Python", "Statistics"],
        "learned_skills": ["Machine Learning", "Recommendation Systems", "Cosine Similarity"],
        "prerequisites": "Pandas basics, basic linear algebra concepts",
        "career_relevance": ["AI/ML Engineer", "Data Scientist"],
        "interests": ["Entertainment", "Productivity"],
        "real_world_problem": "Users struggle to discover new movies they'll actually enjoy among thousands of options.",
        "technologies": ["Python", "Pandas", "Scikit-learn"],
        "learning_outcomes": ["Collaborative filtering", "Content-based filtering", "Cosine similarity"],
        "roadmap": [
            "Get the MovieLens dataset",
            "Build a content-based recommender using genre/description similarity",
            "Build a collaborative filtering recommender using user ratings",
            "Combine both into a hybrid recommendation function",
            "Wrap it in a simple command-line or Flask interface",
        ],
    },
    {
        "title": "Handwritten Digit Recognizer",
        "category": "AI/ML",
        "difficulty": "Medium",
        "estimated_hours": 20,
        "duration_weeks": 2,
        "required_skills": ["Python", "Machine Learning"],
        "learned_skills": ["Neural Networks", "TensorFlow/Keras", "Image Processing"],
        "prerequisites": "Basic ML concepts (training/testing, accuracy)",
        "career_relevance": ["AI/ML Engineer"],
        "interests": ["Education", "Productivity"],
        "real_world_problem": "Manually digitizing handwritten forms and data is slow and error-prone.",
        "technologies": ["Python", "TensorFlow", "Keras"],
        "learning_outcomes": ["CNNs", "Image classification", "Model training basics"],
        "roadmap": [
            "Load the MNIST dataset",
            "Build a simple neural network with Keras",
            "Train and evaluate the model on test data",
            "Improve accuracy using a CNN architecture",
            "Build a small web page to draw a digit and get a live prediction",
        ],
    },
    {
        "title": "AI Resume Screening Tool",
        "category": "AI/ML",
        "difficulty": "Medium",
        "estimated_hours": 22,
        "duration_weeks": 2,
        "required_skills": ["Python", "Flask"],
        "learned_skills": ["NLP", "Text Similarity", "Flask"],
        "prerequisites": "Basic Python and Flask routing",
        "career_relevance": ["AI/ML Engineer", "Backend Developer"],
        "interests": ["Productivity", "College/Student Life"],
        "real_world_problem": "Recruiters spend hours manually screening resumes against job descriptions.",
        "technologies": ["Python", "Flask", "Scikit-learn"],
        "learning_outcomes": ["TF-IDF", "Cosine similarity", "File parsing (PDF/DOCX)"],
        "roadmap": [
            "Build resume text extraction from PDF/DOCX",
            "Build a TF-IDF based relevance scorer vs a job description",
            "Add keyword/skill matching on top of the relevance score",
            "Build a Flask UI to upload resumes and see ranked results",
            "Add a CSV export of the ranked candidates",
        ],
    },
    {
        "title": "Sentiment Analysis on Product Reviews",
        "category": "AI/ML",
        "difficulty": "Medium",
        "estimated_hours": 18,
        "duration_weeks": 2,
        "required_skills": ["Python", "Machine Learning"],
        "learned_skills": ["NLP", "Text Classification", "Data Cleaning"],
        "prerequisites": "Basic ML model training workflow",
        "career_relevance": ["AI/ML Engineer", "Data Scientist"],
        "interests": ["E-commerce", "Productivity"],
        "real_world_problem": "Businesses have thousands of reviews but no quick way to gauge overall customer sentiment.",
        "technologies": ["Python", "NLTK", "Scikit-learn"],
        "learning_outcomes": ["Text cleaning", "Sentiment classification", "Model deployment basics"],
        "roadmap": [
            "Collect a labeled product review dataset",
            "Clean and preprocess review text",
            "Train a classifier (Logistic Regression/Naive Bayes)",
            "Evaluate precision/recall on positive vs negative reviews",
            "Build a simple dashboard showing sentiment breakdown",
        ],
    },

    # ============================================================
    # DATA SCIENCE
    # ============================================================
    {
        "title": "COVID-19 Data Dashboard",
        "category": "Data Science",
        "difficulty": "Easy",
        "estimated_hours": 14,
        "duration_weeks": 1,
        "required_skills": ["Python"],
        "learned_skills": ["Pandas", "Data Visualization", "Plotly/Dash"],
        "prerequisites": "Basic Python, comfort reading CSV data",
        "career_relevance": ["Data Scientist"],
        "interests": ["Healthcare", "Social Good"],
        "real_world_problem": "Public health data is scattered and hard for non-technical people to interpret.",
        "technologies": ["Python", "Pandas", "Plotly"],
        "learning_outcomes": ["Data cleaning", "Interactive charts", "Dashboard basics"],
        "roadmap": [
            "Find a public COVID-19 case dataset",
            "Clean and reshape the data with Pandas",
            "Build interactive charts (cases over time, by region)",
            "Assemble the charts into a simple dashboard",
            "Deploy the dashboard so others can view it",
        ],
    },
    {
        "title": "Student Performance Analysis",
        "category": "Data Science",
        "difficulty": "Easy",
        "estimated_hours": 10,
        "duration_weeks": 1,
        "required_skills": ["Python", "Statistics"],
        "learned_skills": ["Exploratory Data Analysis", "Pandas", "Data Visualization"],
        "prerequisites": "Basic statistics",
        "career_relevance": ["Data Scientist"],
        "interests": ["Education", "College/Student Life"],
        "real_world_problem": "Schools want to understand what factors most affect student grades but data sits unused.",
        "technologies": ["Python", "Pandas", "Seaborn"],
        "learning_outcomes": ["EDA techniques", "Correlation analysis", "Storytelling with data"],
        "roadmap": [
            "Find a student performance dataset",
            "Explore distributions of grades, attendance, study time",
            "Find correlations between factors and performance",
            "Visualize the key findings clearly",
            "Write a short summary of actionable insights",
        ],
    },
    {
        "title": "Sales Forecasting Tool",
        "category": "Data Science",
        "difficulty": "Medium",
        "estimated_hours": 20,
        "duration_weeks": 2,
        "required_skills": ["Python", "Statistics"],
        "learned_skills": ["Time Series Analysis", "Forecasting", "Pandas"],
        "prerequisites": "Basic regression concepts",
        "career_relevance": ["Data Scientist"],
        "interests": ["Finance", "E-commerce"],
        "real_world_problem": "Small businesses struggle to predict next month's demand, leading to overstocking or shortages.",
        "technologies": ["Python", "Statsmodels", "Pandas"],
        "learning_outcomes": ["Time series decomposition", "ARIMA modeling", "Forecast evaluation"],
        "roadmap": [
            "Get historical sales data (daily/monthly)",
            "Visualize trend and seasonality",
            "Build a baseline moving-average forecast",
            "Build an ARIMA model and compare accuracy",
            "Present forecasts for the next 3 months",
        ],
    },
    {
        "title": "Customer Segmentation with Clustering",
        "category": "Data Science",
        "difficulty": "Medium",
        "estimated_hours": 18,
        "duration_weeks": 2,
        "required_skills": ["Python", "Machine Learning"],
        "learned_skills": ["Unsupervised Learning", "K-Means Clustering", "Data Visualization"],
        "prerequisites": "Basic ML concepts",
        "career_relevance": ["Data Scientist"],
        "interests": ["E-commerce", "Finance"],
        "real_world_problem": "Businesses send the same marketing message to everyone instead of targeting distinct customer groups.",
        "technologies": ["Python", "Scikit-learn", "Matplotlib"],
        "learning_outcomes": ["K-Means clustering", "Feature scaling", "Cluster interpretation"],
        "roadmap": [
            "Get a customer purchase dataset",
            "Scale and prepare features for clustering",
            "Apply K-Means and choose the right number of clusters",
            "Visualize and interpret each customer segment",
            "Suggest a marketing strategy per segment",
        ],
    },
    {
        "title": "A/B Testing Analysis Tool",
        "category": "Data Science",
        "difficulty": "Medium",
        "estimated_hours": 16,
        "duration_weeks": 2,
        "required_skills": ["Python", "Statistics"],
        "learned_skills": ["Hypothesis Testing", "Statistical Significance", "Pandas"],
        "prerequisites": "Basic probability and statistics",
        "career_relevance": ["Data Scientist"],
        "interests": ["Productivity", "E-commerce"],
        "real_world_problem": "Teams run A/B tests but often misinterpret whether a result is actually statistically significant.",
        "technologies": ["Python", "SciPy", "Pandas"],
        "learning_outcomes": ["T-tests", "P-values", "Confidence intervals"],
        "roadmap": [
            "Simulate or find A/B test data (control vs variant)",
            "Calculate conversion rates for each group",
            "Run a statistical significance test",
            "Visualize the confidence interval of the difference",
            "Write a clear recommendation based on the result",
        ],
    },

    # ============================================================
    # WEB DEVELOPMENT
    # ============================================================
    {
        "title": "Personal Portfolio Website",
        "category": "Web Development",
        "difficulty": "Easy",
        "estimated_hours": 10,
        "duration_weeks": 1,
        "required_skills": ["HTML/CSS"],
        "learned_skills": ["Responsive Design", "CSS Animations", "JavaScript"],
        "prerequisites": "None - great first project",
        "career_relevance": ["Web Developer", "Full Stack Developer"],
        "interests": ["College/Student Life", "Productivity"],
        "real_world_problem": "Students need an online presence to showcase their work to recruiters.",
        "technologies": ["HTML", "CSS", "JavaScript"],
        "learning_outcomes": ["Responsive layouts", "CSS Flexbox/Grid", "Basic animations"],
        "roadmap": [
            "Plan sections: About, Projects, Skills, Contact",
            "Build the HTML structure",
            "Style it with CSS (Flexbox/Grid, responsive breakpoints)",
            "Add small JS interactions (smooth scroll, dark mode toggle)",
            "Deploy it for free on GitHub Pages",
        ],
    },
    {
        "title": "To-Do List Web App",
        "category": "Web Development",
        "difficulty": "Easy",
        "estimated_hours": 10,
        "duration_weeks": 1,
        "required_skills": ["JavaScript"],
        "learned_skills": ["DOM Manipulation", "Local Storage", "JavaScript"],
        "prerequisites": "Basic HTML/CSS",
        "career_relevance": ["Web Developer"],
        "interests": ["Productivity", "College/Student Life"],
        "real_world_problem": "People need a lightweight, no-signup way to track daily tasks.",
        "technologies": ["HTML", "CSS", "JavaScript"],
        "learning_outcomes": ["DOM manipulation", "Event handling", "Browser local storage"],
        "roadmap": [
            "Build the HTML structure (input, list, buttons)",
            "Style it with CSS",
            "Add JS to create, complete, and delete tasks",
            "Persist tasks using localStorage so they survive refresh",
            "Add filtering (all/active/completed)",
        ],
    },
    {
        "title": "Blog Platform with Flask",
        "category": "Web Development",
        "difficulty": "Medium",
        "estimated_hours": 24,
        "duration_weeks": 2,
        "required_skills": ["Python", "HTML/CSS", "SQL"],
        "learned_skills": ["Flask", "SQLite", "Authentication Basics"],
        "prerequisites": "Basic Python and HTML",
        "career_relevance": ["Web Developer", "Full Stack Developer", "Backend Developer"],
        "interests": ["Productivity", "Education"],
        "real_world_problem": "Writers need a simple self-hosted platform instead of relying on third-party blogging sites.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["Flask routing", "Database CRUD", "Basic authentication"],
        "roadmap": [
            "Design the database: users and posts tables",
            "Build routes for creating, editing, deleting posts",
            "Add simple login (no need for full security for v1)",
            "Style the blog with a clean CSS theme",
            "Deploy the finished blog online",
        ],
    },
    {
        "title": "E-Commerce Product Page Clone",
        "category": "Web Development",
        "difficulty": "Medium",
        "estimated_hours": 20,
        "duration_weeks": 2,
        "required_skills": ["JavaScript", "HTML/CSS"],
        "learned_skills": ["React", "Component Design", "State Management"],
        "prerequisites": "Solid HTML/CSS/JS basics",
        "career_relevance": ["Web Developer", "Full Stack Developer"],
        "interests": ["E-commerce"],
        "real_world_problem": "Many beginners struggle to build realistic, interactive UIs like real shopping sites use.",
        "technologies": ["React", "CSS", "JavaScript"],
        "learning_outcomes": ["React components", "Props and state", "Cart logic"],
        "roadmap": [
            "Set up a React project",
            "Build a product listing grid from sample data",
            "Build a product detail page with image gallery",
            "Add an in-memory shopping cart with add/remove",
            "Polish the UI to look production-ready",
        ],
    },
    {
        "title": "Real-Time Chat Application",
        "category": "Web Development",
        "difficulty": "Hard",
        "estimated_hours": 30,
        "duration_weeks": 3,
        "required_skills": ["JavaScript", "Node.js"],
        "learned_skills": ["WebSockets", "Real-Time Systems", "Node.js"],
        "prerequisites": "Comfortable with JavaScript and basic backend concepts",
        "career_relevance": ["Web Developer", "Full Stack Developer", "Backend Developer"],
        "interests": ["Productivity", "Social Good"],
        "real_world_problem": "Teams and communities need lightweight real-time communication without heavy third-party tools.",
        "technologies": ["Node.js", "Socket.io", "Express"],
        "learning_outcomes": ["WebSocket communication", "Real-time event handling", "Room-based chat logic"],
        "roadmap": [
            "Set up a Node.js + Express server",
            "Add Socket.io for real-time messaging",
            "Build the chat UI (message list, input box)",
            "Add chat rooms/usernames",
            "Deploy and test with multiple users",
        ],
    },

    # ============================================================
    # BACKEND DEVELOPMENT
    # ============================================================
    {
        "title": "REST API for a Library System",
        "category": "Backend Development",
        "difficulty": "Easy",
        "estimated_hours": 14,
        "duration_weeks": 1,
        "required_skills": ["Python", "SQL"],
        "learned_skills": ["REST APIs", "Flask", "Database Design"],
        "prerequisites": "Basic Python and SQL",
        "career_relevance": ["Backend Developer", "Full Stack Developer"],
        "interests": ["Education", "College/Student Life"],
        "real_world_problem": "Small libraries manage book borrowing manually with no digital tracking.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["REST API design", "CRUD endpoints", "Database relationships"],
        "roadmap": [
            "Design tables: books, members, borrow_records",
            "Build CRUD endpoints for books and members",
            "Add borrow/return endpoints with due-date logic",
            "Add basic input validation",
            "Document the API endpoints",
        ],
    },
    {
        "title": "URL Shortener Service",
        "category": "Backend Development",
        "difficulty": "Easy",
        "estimated_hours": 10,
        "duration_weeks": 1,
        "required_skills": ["Python", "SQL"],
        "learned_skills": ["Flask", "Hashing/Encoding", "Redirects"],
        "prerequisites": "Basic Flask routing",
        "career_relevance": ["Backend Developer"],
        "interests": ["Productivity"],
        "real_world_problem": "Long URLs are hard to share, especially in messages with character limits.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["URL encoding schemes", "Redirect handling", "Basic analytics tracking"],
        "roadmap": [
            "Design a table mapping short codes to long URLs",
            "Build the shorten endpoint (generate a short code)",
            "Build the redirect route",
            "Track click counts per short URL",
            "Build a minimal frontend to test it",
        ],
    },
    {
        "title": "Food Delivery Backend System",
        "category": "Backend Development",
        "difficulty": "Hard",
        "estimated_hours": 35,
        "duration_weeks": 3,
        "required_skills": ["Python", "SQL", "REST APIs"],
        "learned_skills": ["System Design", "Order Management", "API Architecture"],
        "prerequisites": "Comfortable building REST APIs already",
        "career_relevance": ["Backend Developer", "Full Stack Developer"],
        "interests": ["E-commerce", "Productivity"],
        "real_world_problem": "Small local restaurants have no affordable way to run their own ordering system.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["Multi-entity system design", "Order state machines", "API architecture"],
        "roadmap": [
            "Design tables: restaurants, menu items, orders, order_items",
            "Build endpoints for browsing restaurants/menus",
            "Build order placement and status update endpoints",
            "Add order status flow (placed then preparing then delivered)",
            "Add a simple admin view to manage incoming orders",
        ],
    },
    {
        "title": "Job Queue / Task Scheduler",
        "category": "Backend Development",
        "difficulty": "Medium",
        "estimated_hours": 18,
        "duration_weeks": 2,
        "required_skills": ["Python"],
        "learned_skills": ["Background Jobs", "Scheduling", "Concurrency Basics"],
        "prerequisites": "Comfortable with Python functions and basic backend concepts",
        "career_relevance": ["Backend Developer"],
        "interests": ["Productivity"],
        "real_world_problem": "Apps often need to run tasks (emails, reports) in the background without blocking users.",
        "technologies": ["Python", "SQLite"],
        "learning_outcomes": ["Job queues", "Scheduling logic", "Retry handling"],
        "roadmap": [
            "Design a jobs table (task, status, run_at)",
            "Build a function to enqueue new jobs",
            "Build a worker loop that picks up and runs due jobs",
            "Add retry logic for failed jobs",
            "Build a simple dashboard to view job status",
        ],
    },

    # ============================================================
    # CYBERSECURITY
    # ============================================================
    {
        "title": "Password Strength Analyzer",
        "category": "Cybersecurity",
        "difficulty": "Easy",
        "estimated_hours": 8,
        "duration_weeks": 1,
        "required_skills": ["Python"],
        "learned_skills": ["Cybersecurity Basics", "Regex", "Password Policies"],
        "prerequisites": "Basic Python",
        "career_relevance": ["Cybersecurity Analyst"],
        "interests": ["Productivity", "Social Good"],
        "real_world_problem": "Many users still pick weak, easily-guessed passwords, leading to account breaches.",
        "technologies": ["Python"],
        "learning_outcomes": ["Regex pattern matching", "Entropy calculation", "Security best practices"],
        "roadmap": [
            "Research common password strength criteria",
            "Build rules for length, character variety, common patterns",
            "Calculate a strength score/entropy estimate",
            "Check against a list of commonly leaked passwords",
            "Build a simple CLI or web form for testing passwords",
        ],
    },
    {
        "title": "Network Port Scanner",
        "category": "Cybersecurity",
        "difficulty": "Medium",
        "estimated_hours": 14,
        "duration_weeks": 1,
        "required_skills": ["Python", "Networking"],
        "learned_skills": ["Sockets", "Networking Fundamentals", "Cybersecurity Basics"],
        "prerequisites": "Basic networking concepts (IP, ports)",
        "career_relevance": ["Cybersecurity Analyst"],
        "interests": ["Social Good"],
        "real_world_problem": "Admins need to quickly check which ports are open on a machine to spot vulnerabilities.",
        "technologies": ["Python", "Sockets"],
        "learning_outcomes": ["TCP sockets", "Port scanning techniques", "Basic network security"],
        "roadmap": [
            "Learn how TCP connections and ports work",
            "Write a function to test if a single port is open",
            "Scan a range of ports on a target IP",
            "Add multithreading to speed up scanning",
            "Output a clean report of open ports and known services",
        ],
    },
    {
        "title": "Phishing URL Detector",
        "category": "Cybersecurity",
        "difficulty": "Medium",
        "estimated_hours": 18,
        "duration_weeks": 2,
        "required_skills": ["Python", "Machine Learning"],
        "learned_skills": ["Feature Engineering", "Classification", "Cybersecurity Basics"],
        "prerequisites": "Basic ML model training",
        "career_relevance": ["Cybersecurity Analyst", "AI/ML Engineer"],
        "interests": ["Social Good", "Productivity"],
        "real_world_problem": "Phishing links trick users into giving up credentials, and manual detection doesn't scale.",
        "technologies": ["Python", "Scikit-learn"],
        "learning_outcomes": ["URL feature extraction", "Binary classification", "Model evaluation"],
        "roadmap": [
            "Get a labeled phishing vs legitimate URL dataset",
            "Extract features (URL length, symbols, domain age, etc.)",
            "Train a classifier to detect phishing URLs",
            "Evaluate false positive/negative rates",
            "Build a simple checker tool for new URLs",
        ],
    },
    {
        "title": "File Integrity Checker",
        "category": "Cybersecurity",
        "difficulty": "Easy",
        "estimated_hours": 10,
        "duration_weeks": 1,
        "required_skills": ["Python"],
        "learned_skills": ["Hashing", "File Systems", "Cybersecurity Basics"],
        "prerequisites": "Basic Python file handling",
        "career_relevance": ["Cybersecurity Analyst"],
        "interests": ["Productivity"],
        "real_world_problem": "Important files can be silently modified or corrupted without anyone noticing.",
        "technologies": ["Python", "Hashlib"],
        "learning_outcomes": ["Hashing algorithms (SHA-256)", "File monitoring", "Change detection"],
        "roadmap": [
            "Write a function to hash a file's contents",
            "Store baseline hashes for a folder of files",
            "Write a checker that compares current hashes to baseline",
            "Flag any changed/missing/new files",
            "Add a scheduled scan mode",
        ],
    },

    # ============================================================
    # APP DEVELOPMENT
    # ============================================================
    {
        "title": "Habit Tracker Mobile App",
        "category": "App Development",
        "difficulty": "Easy",
        "estimated_hours": 16,
        "duration_weeks": 2,
        "required_skills": ["Flutter"],
        "learned_skills": ["Mobile UI Design", "Local Storage", "State Management"],
        "prerequisites": "Basic Dart/Flutter syntax",
        "career_relevance": ["App Developer"],
        "interests": ["Productivity"],
        "real_world_problem": "People want to build good habits but forget to track them consistently.",
        "technologies": ["Flutter", "Dart"],
        "learning_outcomes": ["Flutter widgets", "Local data persistence", "Simple state management"],
        "roadmap": [
            "Design the habit list screen",
            "Add functionality to create/check off habits",
            "Persist data locally (shared preferences or SQLite)",
            "Add a simple streak counter",
            "Polish the UI with a clean, motivating design",
        ],
    },
    {
        "title": "Campus Navigation App",
        "category": "App Development",
        "difficulty": "Medium",
        "estimated_hours": 24,
        "duration_weeks": 2,
        "required_skills": ["Flutter"],
        "learned_skills": ["Maps Integration", "Location Services", "Mobile UI Design"],
        "prerequisites": "Comfortable with Flutter basics",
        "career_relevance": ["App Developer"],
        "interests": ["College/Student Life", "Education"],
        "real_world_problem": "New students often get lost finding classrooms, labs, and offices on a large campus.",
        "technologies": ["Flutter", "Google Maps API"],
        "learning_outcomes": ["Map integration", "Location markers", "Search functionality"],
        "roadmap": [
            "Set up map integration in the app",
            "Add markers for key campus buildings",
            "Add a search bar to find locations",
            "Add basic directions between two points",
            "Test with real campus coordinates",
        ],
    },
    {
        "title": "Expense Splitter App",
        "category": "App Development",
        "difficulty": "Medium",
        "estimated_hours": 20,
        "duration_weeks": 2,
        "required_skills": ["Flutter"],
        "learned_skills": ["State Management", "Local Database", "UI Design"],
        "prerequisites": "Basic Flutter and Dart",
        "career_relevance": ["App Developer"],
        "interests": ["Finance", "College/Student Life"],
        "real_world_problem": "Friends splitting shared expenses (trips, rent, meals) lose track of who owes whom.",
        "technologies": ["Flutter", "SQLite"],
        "learning_outcomes": ["Local database design", "Calculation logic", "Multi-screen navigation"],
        "roadmap": [
            "Design the group and expense data model",
            "Build screens to add groups, members, and expenses",
            "Implement the split calculation logic",
            "Show a summary of who owes whom",
            "Add basic settle-up tracking",
        ],
    },

    # ============================================================
    # PRODUCTIVITY
    # ============================================================
    {
        "title": "AI Study Planner",
        "category": "Productivity",
        "difficulty": "Medium",
        "estimated_hours": 20,
        "duration_weeks": 2,
        "required_skills": ["Python", "Flask"],
        "learned_skills": ["Scheduling Algorithms", "Flask", "AI API Integration"],
        "prerequisites": "Basic Flask and Python",
        "career_relevance": ["Web Developer", "AI/ML Engineer"],
        "interests": ["Education", "College/Student Life"],
        "real_world_problem": "Students struggle to build a realistic study timetable around their exams and free time.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["Scheduling logic", "Form handling", "Basic AI integration"],
        "roadmap": [
            "Collect subjects, exam dates, and free time slots",
            "Build a basic scheduling algorithm to distribute study time",
            "Store and display the generated timetable",
            "Add the ability to mark sessions complete",
            "Add reminders for upcoming exams",
        ],
    },
    {
        "title": "Note-Taking App with Tags",
        "category": "Productivity",
        "difficulty": "Easy",
        "estimated_hours": 12,
        "duration_weeks": 1,
        "required_skills": ["Python", "Flask"],
        "learned_skills": ["CRUD Operations", "Search/Filtering", "Flask"],
        "prerequisites": "Basic Flask routing",
        "career_relevance": ["Web Developer", "Backend Developer"],
        "interests": ["Productivity", "Education"],
        "real_world_problem": "Plain note apps make it hard to organize and later find notes by topic.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["CRUD operations", "Tag-based filtering", "Search functionality"],
        "roadmap": [
            "Design the notes table with a tags field",
            "Build create/edit/delete note functionality",
            "Add tag-based filtering",
            "Add a search bar across note content",
            "Polish with a clean, distraction-free UI",
        ],
    },
    {
        "title": "Pomodoro Focus Timer",
        "category": "Productivity",
        "difficulty": "Easy",
        "estimated_hours": 8,
        "duration_weeks": 1,
        "required_skills": ["JavaScript"],
        "learned_skills": ["Timers", "DOM Manipulation", "Browser Notifications"],
        "prerequisites": "Basic HTML/CSS/JS",
        "career_relevance": ["Web Developer"],
        "interests": ["Productivity", "College/Student Life"],
        "real_world_problem": "People struggle to stay focused for long stretches without a structured work/break rhythm.",
        "technologies": ["HTML", "CSS", "JavaScript"],
        "learning_outcomes": ["JS timers", "Browser notifications", "UI state management"],
        "roadmap": [
            "Build the timer UI (start/pause/reset)",
            "Implement the work/break countdown logic",
            "Add a sound/notification when a session ends",
            "Add a session counter for the day",
            "Add customizable work/break durations",
        ],
    },

    # ============================================================
    # COLLEGE / STUDENT PROBLEMS
    # ============================================================
    {
        "title": "Smart Attendance System (Face Recognition)",
        "category": "College/Student Problems",
        "difficulty": "Hard",
        "estimated_hours": 32,
        "duration_weeks": 3,
        "required_skills": ["Python", "Machine Learning"],
        "learned_skills": ["Computer Vision", "Face Recognition", "OpenCV"],
        "prerequisites": "Basic Python and comfort installing ML libraries",
        "career_relevance": ["AI/ML Engineer"],
        "interests": ["Education", "College/Student Life"],
        "real_world_problem": "Manual attendance wastes class time and is vulnerable to proxy attendance.",
        "technologies": ["Python", "OpenCV", "face_recognition library"],
        "learning_outcomes": ["Face detection", "Face encoding/matching", "Camera integration"],
        "roadmap": [
            "Set up OpenCV and a face recognition library",
            "Build a script to register student faces",
            "Build real-time face detection from a webcam feed",
            "Match detected faces against registered students",
            "Log attendance automatically to a database",
        ],
    },
    {
        "title": "Campus Lost & Found Portal",
        "category": "College/Student Problems",
        "difficulty": "Easy",
        "estimated_hours": 14,
        "duration_weeks": 1,
        "required_skills": ["Python", "Flask"],
        "learned_skills": ["CRUD Operations", "File Uploads", "Flask"],
        "prerequisites": "Basic Flask",
        "career_relevance": ["Web Developer", "Backend Developer"],
        "interests": ["College/Student Life", "Social Good"],
        "real_world_problem": "Lost items on campus rarely make it back to their owners due to no central reporting system.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["Image uploads", "Search/filter logic", "CRUD operations"],
        "roadmap": [
            "Design the lost-items table (with image, location, date)",
            "Build a form to report a found/lost item with photo upload",
            "Build a searchable listing page",
            "Add a simple 'mark as claimed' feature",
            "Add category filters (electronics, documents, etc.)",
        ],
    },
    {
        "title": "Timetable Clash Detector",
        "category": "College/Student Problems",
        "difficulty": "Easy",
        "estimated_hours": 10,
        "duration_weeks": 1,
        "required_skills": ["Python"],
        "learned_skills": ["Algorithms", "Data Structures", "Logic Building"],
        "prerequisites": "Basic Python and lists/dictionaries",
        "career_relevance": ["Backend Developer", "Web Developer"],
        "interests": ["College/Student Life", "Education"],
        "real_world_problem": "Students manually cross-check elective timetables for overlaps, which is tedious and error-prone.",
        "technologies": ["Python"],
        "learning_outcomes": ["Interval overlap logic", "Data structure design", "Input validation"],
        "roadmap": [
            "Design a way to represent each class's day/time slot",
            "Write a function to detect overlapping time slots",
            "Allow a student to input their selected electives",
            "Flag and clearly report any clashes",
            "Wrap it in a simple web form",
        ],
    },
    {
        "title": "Peer Doubt-Solving Forum",
        "category": "College/Student Problems",
        "difficulty": "Medium",
        "estimated_hours": 22,
        "duration_weeks": 2,
        "required_skills": ["Python", "Flask", "SQL"],
        "learned_skills": ["Forum/Thread Design", "Flask", "Database Relationships"],
        "prerequisites": "Basic Flask and SQL",
        "career_relevance": ["Web Developer", "Backend Developer", "Full Stack Developer"],
        "interests": ["Education", "College/Student Life", "Social Good"],
        "real_world_problem": "Students post doubts across scattered WhatsApp groups where answers get lost.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["Thread/reply data modeling", "Upvoting logic", "Basic moderation"],
        "roadmap": [
            "Design tables for questions, answers, and votes",
            "Build post/answer creation functionality",
            "Add upvote/downvote on answers",
            "Add subject-based filtering/tagging",
            "Sort questions by unanswered/most active",
        ],
    },
    {
        "title": "Placement Preparation Tracker",
        "category": "College/Student Problems",
        "difficulty": "Easy",
        "estimated_hours": 12,
        "duration_weeks": 1,
        "required_skills": ["Python", "Flask"],
        "learned_skills": ["CRUD Operations", "Progress Tracking", "Flask"],
        "prerequisites": "Basic Flask",
        "career_relevance": ["Web Developer", "Backend Developer"],
        "interests": ["College/Student Life", "Productivity"],
        "real_world_problem": "Students preparing for placements juggle DSA topics, mock interviews, and company research with no central tracker.",
        "technologies": ["Python", "Flask", "SQLite"],
        "learning_outcomes": ["Progress tracking UI", "CRUD operations", "Simple analytics"],
        "roadmap": [
            "Design a checklist of DSA topics and companies to prep for",
            "Build functionality to mark topics as done/in-progress",
            "Add a section to log mock interview notes",
            "Show overall preparation progress as a percentage",
            "Add simple reminders for upcoming application deadlines",
        ],
    },
]


def seed_if_needed():
    """
    Inserts all projects above into the database, but ONLY if the
    projects table is currently empty. This makes it safe to call
    every time the app starts without creating duplicate rows.
    """
    if models.count_projects() == 0:
        for project in PROJECTS:
            models.insert_project(project)
        print(f"Seeded {len(PROJECTS)} projects into the database.")
